services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: rfid_mqtt_broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - rfid_network

  postgres:
    image: postgres:15-alpine
    container_name: rfid_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_cabinet
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cabinet_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rfid_network

  backend:
    build: ./backend
    container_name: rfid_backend_api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000" # Exponemos el puerto para que también puedas probar en localhost
    depends_on:
      - mosquitto
      - postgres
    networks:
      - rfid_network

  # ==========================================
  # NUEVO SERVICIO: TÚNEL NGROK
  # ==========================================
  ngrok:
    image: ngrok/ngrok:latest
    container_name: rfid_ngrok_tunnel
    restart: always
    # Ngrok buscará al contenedor llamado "backend" en su puerto interno 3000
    command: "http rfid_backend_api:3000"
    environment:
      # Pega aquí tu token real (sin comillas)
      - NGROK_AUTHTOKEN=3GgydGjsLPIHRTRrHbvL4JPEzSG_2Mj2L1vUXzzZ6SffqLGBN
    ports:
      - "4040:4040" # Puerto para ver el panel de control local de ngrok
    depends_on:
      - backend
    networks:
      - rfid_network

networks:
  rfid_network:
    driver: bridge