name: rfid-cabinet-system

x-backend-base: &backend-base
  build:
    context: ./backend
    dockerfile: Dockerfile
  restart: unless-stopped
  networks:
    - default
    - rfid_internal

x-frontend-base: &frontend-base
  build:
    context: ./Front-cabinet
    dockerfile: Dockerfile
    target: production-stage
  restart: unless-stopped

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: rfid_mqtt_broker
    profiles: ["dev", "prod"]
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  postgres:
    image: postgres:15-alpine
    container_name: rfid_postgres
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rfid_internal

  backend:
    container_name: rfid_backend
    profiles: ["dev", "prod"]
    env_file:
      - .env 
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
      - postgres
    <<: *backend-base

  frontend:
    container_name: rfid_frontend
    profiles: ["dev", "prod"]
    ports:
      - "80:80"   
      - "5173:5173" 
    volumes:
      - ./Front-cabinet:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    <<: *frontend-base

  ngrok-tunnel:
    image: ngrok/ngrok:alpine
    container_name: rfid_ngrok_tunnel
    profiles: ["prod"]
    restart: unless-stopped
    command: 
      - "http"
      - "backend:3000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  frontend_node_modules:
  mosquitto_data:
  mosquitto_log:

networks:
  rfid_internal:
    driver: bridge
    internal: true
  default:
    name: rfid_external
    driver: bridge
